apiVersion: v1
kind: Service
metadata:
  name: backend-luis-tasayco-deployment
  namespace: luis-tasayco-namespace
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: backend-luis-tasayco-deployment