version: '3.8'

services:
  front:
    image: luistasayco2004/angular_monitoreo:lastet
    container_name: front_monitoreo
    ports:
      - "4200:4200"
    environment:
      API_BACKEND : 'https://fuzzy-telegram-6jgr9qvgg9gfrpw7-8080.app.github.dev/'

  back:
    image: luistasayco2004/spring-boot-monitoreo_prs:lastet
    container_name: back_monitoreo
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: r2dbc:pool:postgresql://ep-patient-glade-a500n7jv.us-east-2.aws.neon.tech/neondb?sslmode=require
      DATABASE_USERNAME: neondb_owner
      DATABASE_PASSWORD: E7ZoFl2PrvjX