# kubectl apply -f deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-moderator-fe
  namespace: luis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-moderator-fe
  template:
    metadata:
      labels:
        app: content-moderator-fe
    spec:
      containers:
      - name: content-moderator-fe
        image: luistasayco2004/angular_monitoreo:lastet
        env:
        - name: API_BACKEND
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: API_BACKEND
        # resources:
        #   requests:
        #     memory: "512Mi"
        #     cpu: "500m"
        #   limits:
        #     memory: "1Gi"
        #     cpu: "1"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-moderator-be
  namespace: luis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: content-moderator-be
  template:
    metadata:
      labels:
        app: content-moderator-be
    spec:
      containers:
      - name: content-moderator-be
        image: luistasayco2004/spring-boot-monitoreo_prs:lastet
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: DATABASE_URL
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: DATABASE_USERNAME
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: DATABASE_PASSWORD
        resources:
          requests:
            memory: "128Mi"  # Memoria solicitada para el contenedor
            cpu: "500m"      # CPU solicitada para el contenedor
          limits:
            memory: "256Mi"  # Límite de memoria
            cpu: "1"  
